"""Vendor pinned OFL fonts. Run manually with fonttools[woff] 4.59.0 + brotli 1.1.0.

Full font coverage is retained; native-name subsets keep OpenType shaping closure.
This is a maintenance tool, not a dependency of the normal app build.
"""
import hashlib
import io
import json
from pathlib import Path
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor

from fontTools import subset
from fontTools.ttLib import TTFont

APP = Path(__file__).resolve().parents[2]
CONFIG = json.loads(Path(__file__).with_name('sources.json').read_text())
LANGUAGES = json.loads((APP / 'src/i18n/languages.json').read_text())
DEST = APP / 'public/fonts'
DEST.mkdir(exist_ok=True)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read()


def ranges(points):
    blocks = []
    for point in sorted(points):
        if blocks and blocks[-1][1] + 1 == point:
            blocks[-1][1] = point
        else:
            blocks.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in blocks)


def write_font(font, stem):
    font.flavor = 'woff2'
    output = io.BytesIO()
    font.save(output, reorderTables=True)
    data = output.getvalue()
    filename = f'{stem}-{sha(data)[:12]}.woff2'
    (DEST / filename).write_bytes(data)
    return {'url': f'/fonts/{filename}', 'bytes': len(data), 'sha256': sha(data)}


def generate(item):
    script, source = item
    base = f"https://raw.githubusercontent.com/google/fonts/{CONFIG['revision']}/ofl/{source['directory']}/"
    url = base + urllib.parse.quote(source['file'])
    raw = fetch(url)
    license_data = fetch(base + 'OFL.txt')
    license_name = f"{source['directory']}-OFL.txt"
    (DEST / license_name).write_bytes(license_data)
    font = TTFont(io.BytesIO(raw), recalcTimestamp=False)
    coverage = set(font.getBestCmap())
    full = write_font(font, f'{script}-full')
    native_font = TTFont(io.BytesIO(raw), recalcTimestamp=False)
    native_name = LANGUAGES[source['language']]['nativeName']
    assert set(map(ord, native_name)) <= coverage, native_name
    opts = subset.Options()
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.name_languages = ['*']
    opts.notdef_outline = True
    sub = subset.Subsetter(options=opts)
    sub.populate(text=native_name)
    sub.subset(native_font)
    # Name the modified native subset explicitly, retaining author/license records.
    native_family = f'Morpher Native {script}'
    for record in native_font['name'].names:
        if record.nameID in (1, 4, 6, 16):
            name = native_family.replace(' ', '') if record.nameID == 6 else native_family
            record.string = name.encode(record.getEncoding())
    native = write_font(native_font, f'{script}-native')
    native['family'] = native_family
    native['unicodeRange'] = ranges(map(ord, native_name))
    full.update(family=source['family'], unicodeRange=ranges(coverage), glyphCount=len(font.getGlyphOrder()))
    print(script, 'full', full['bytes'], 'native', native['bytes'], flush=True)
    return script, {'family': source['family'], 'source': url, 'sourceSha256': sha(raw),
                    'license': f'/fonts/{license_name}', 'full': full, 'native': native}


if __name__ == '__main__':
    with ThreadPoolExecutor(max_workers=3) as pool:
        fonts = dict(pool.map(generate, CONFIG['families'].items()))
    (APP / 'src/i18n/fonts.json').write_text(json.dumps(fonts, ensure_ascii=False, indent=2) + '\n')
    print('Total full bytes:', sum(f['full']['bytes'] for f in fonts.values()))
    print('Total native bytes:', sum(f['native']['bytes'] for f in fonts.values()))

    css = ['/* Generated by scripts/fonts/generate.py — native language names only. */']
    for spec in fonts.values():
        native = spec['native']
        css.append(f'''@font-face {{
  font-family: "{native['family']}";
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url("{native['url']}") format("woff2");
  unicode-range: {native['unicodeRange']};
}}''')
    (APP / 'src/styles/native-fonts.css').write_text('\n\n'.join(css) + '\n')
