"""Generate small self-hosted fallbacks for the studio's math and key symbols."""
import io
import json
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
from generate import APP, CONFIG, DEST, fetch, ranges, sha, write_font


def make_font(raw, text, family, stem):
    font = TTFont(io.BytesIO(raw), recalcTimestamp=False)
    assert set(map(ord, text)) <= set(font.getBestCmap()), family
    opts = subset.Options()
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.name_languages = ['*']
    sub = subset.Subsetter(options=opts)
    sub.populate(text=text)
    sub.subset(font)
    for record in font['name'].names:
        if record.nameID in (1, 4, 6, 16):
            value = family.replace(' ', '') if record.nameID == 6 else family
            record.string = value.encode(record.getEncoding())
    result = write_font(font, stem)
    result.update(family=family, unicodeRange=ranges(map(ord, text)), sourceSha256=sha(raw))
    return result


if __name__ == '__main__':
    fonts = json.loads((APP / 'src/i18n/fonts.json').read_text())
    math_source = fonts['cyrillic']['source']
    symbols_base = f"https://raw.githubusercontent.com/google/fonts/{CONFIG['revision']}/ofl/notosanssymbols2/"
    symbols_source = symbols_base + 'NotoSansSymbols2-Regular.ttf'
    (DEST / 'notosanssymbols2-OFL.txt').write_bytes(fetch(symbols_base + 'OFL.txt'))
    math = make_font(fetch(math_source), 'λτ', 'Morpher Math', 'math')
    math.update(source=math_source, license='/fonts/notosans-OFL.txt', weight='400 700')
    symbols = make_font(fetch(symbols_source), '⌥⏎▶◀◆', 'Morpher Symbols', 'symbols')
    symbols.update(source=symbols_source, license='/fonts/notosanssymbols2-OFL.txt', weight='400')
    arrows_base = f"https://raw.githubusercontent.com/google/fonts/{CONFIG['revision']}/ofl/notosanssymbols/"
    arrows_source = arrows_base + 'NotoSansSymbols%5Bwght%5D.ttf'
    (DEST / 'notosanssymbols-OFL.txt').write_bytes(fetch(arrows_base + 'OFL.txt'))
    arrows = make_font(fetch(arrows_source), '←→↔', 'Morpher Arrows', 'arrows')
    arrows.update(source=arrows_source, license='/fonts/notosanssymbols-OFL.txt', weight='400 700')
    shared = [math, symbols, arrows]
    (APP / 'src/i18n/shared-fonts.json').write_text(json.dumps(shared, ensure_ascii=False, indent=2) + '\n')
    css = ['/* Generated by scripts/fonts/shared.py. */']
    for font in shared:
        css.append(f'''@font-face {{
  font-family: "{font['family']}";
  font-style: normal;
  font-weight: {font['weight']};
  font-display: swap;
  src: url("{font['url']}") format("woff2");
  unicode-range: {font['unicodeRange']};
}}''')
    (APP / 'src/styles/shared-fonts.css').write_text('\n\n'.join(css) + '\n')
    print([(font['family'], font['bytes']) for font in shared])
